### ISSUE TITLE
objects.keys

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#103]
Return an array of an objects enumerable keys

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

To accomplish this, must convert object to array, options include:
- native Object.entries and reduce to just keys
- native Object.keys(serve as alias)

## References 

 - [Object.keys()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)

**Comment by evanplaice** [comment]
Added in 0.46

**Comment by evanplaice** [comment]
Removed in 0.74.9
