### ISSUE TITLE
objects.invert

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#105]
Creates a new object with key-value pairs inverted, in the case of duplicate values the latter value will overwrite the previous

## Checklist

- [ ] implementation
- [ ] tests
- [ ] jsdoc

## Details

```
const res = Objects.invert({ a: 1, b: 2, c: 1 });
console.log(res);
> { '1': 'c', '2': 'b' }
```

## References 

 - [_.invert](https://lodash.com/docs/4.17.15#invert)

**Comment by evanplaice** [comment]
FYI, if you want to take on `arrays.frequency` it's all yours.

**Comment by evanplaice** [comment]
@jkvyff Your work on objects.invert got pushed to the master branch and some of the tests are failing.

https://github.com/vanillaes/absurdum/commit/6832265dc3e3ecec800e5f6ed9483ee603eb4d0b/checks?check_suite_id=350350872

**Comment by jkvyff** [comment]
My mistake, I switched branches before making the changes to the tests.

**Comment by evanplaice** [comment]
It's all good

Not publishing a broken build to NPM is what matters and the CD pre-checks make that impossible. 😁

**Comment by evanplaice** [comment]
Added in 0.47
