### ISSUE TITLE
Objects.pick

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#108]
Creates a new object from properties selected by their key values as strings or an array of strings

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
const result = Objects.pick({ a: 'mixed', b34: 'toast', 45: 'pasta' }, 'a', 45);
console.log(result);
> { 45: 'pasta', a: 'mixed' }
```

## References 
 - [_pick](https://lodash.com/docs/4.17.15#pick)

**Comment by evanplaice** [comment]
Added in 0.50
