### ISSUE TITLE
Add objects.create

### ISSUE THREAD

**Issue by evanplaice** [vanillaes/absurdum#113]
Creates an object that inherits from the prototype object. If a properties object is given, its own enumerable string keyed properties are assigned to the created object.

## Checklist

- [ ] implementation
- [ ] tests
- [ ] jsdoc

## References 

 - [_.create](https://lodash.com/docs/#create)

**Comment by jkvyff** [comment]
As part of an implementation of a create method, one would probably need to use:
 [Object.setPrototypeOf()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf)
Though there appears to be problems with implementing this with good performance.

Also, any implementation would probably require new, create, or a syntactic sugar version of them. However, "new" calls the constructor function while Object.create does not resulting in extra work.

It may be best to use as an alias for Object.create. Let me know what you think.

**Comment by evanplaice** [comment]
We could prune this function altogether. At some point, I'll probably end up removing most/all of the functions that are duplicates of built-ins anyway.

**Comment by jkvyff** [comment]
I'm good with that as well.

**Comment by evanplaice** [comment]
How do you feel about changing the focus of this project? Instead of 'just for practice', start promoting it as a general purpose utility library.

The design should hold up. Every operator is stand-alone which is optimal for tree shaking. Every operator is idempotent because reduce. And perf should hold up against the alternatives.

BTW, you should be included in `package.json` as a co-author. You've done as much or more work than me on this project.

**Comment by evanplaice** [comment]
Since `pkg.author` is only meant for one name, I switched it to `pkg.contributors' so you can add your info if you'd like.

**Comment by jkvyff** [comment]
That makes sense, I have loved it being consistently idempotent, removes a whole category of bugs.
Also, allows for easy modifications for specific functionality.
