### ISSUE TITLE
Add objects.values

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#114]
Values should return all values from an object in an array

## Checklist

- [ ] implementation
- [ ] tests
- [ ] jsdoc

## Details
Recommendation to add as an alias for Object.values for same reason as Objects.keys

```
const obj = {
  a: 'somestring',
  b: 42,
  c: false
};
console.log(Objects.values(obj));
> ["somestring", 42, false]
```

## References 

- [Object.values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values)
 - [_.values](https://lodash.com/docs/4.17.15#values)

**Comment by evanplaice** [comment]
Added in 0.51
