### ISSUE TITLE
Add objects.findKey

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#117]
FindKey will return the key value of the first object value it encounters that matches or returns true for the predicate

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details
A slight amalgam of version 3 and 4 of Lodash's implementation, with allowing for both array selection notation as well as a 'this' argument.

```
const users = {
  'barney':  { 'age': 36, 'active': true },
  'fred':    { 'age': 40, 'active': false },
  'pebbles': { 'age': 1,  'active': true }
};
 
Objects.findKey(users, function(chr) {
  return chr.age < 40;
});
// => 'barney' (iteration order is not guaranteed)
 
Objects.findKey(users, { 'age': 1, 'active': true });
// => 'pebbles'
 
Objects.findKey(users, ['active', false]);
// => 'fred'
 
Objects.findKey(users, 'active');
// => 'barney'
```

## References 
 - [_.findKey](https://lodash.com/docs/3.10.1#findKey)

**Comment by evanplaice** [comment]
Added in 0.52
