### ISSUE TITLE
objects.mapKeys

### ISSUE THREAD

**Issue by reed-jones** [vanillaes/absurdum#122]
Creates a new object with the same values as the original, but with each key transformed using the supplied function.
```js
/**
 * const result = objects.mapKeys({ a: 1, b: 2, c: 3 }, (value, key, object) => `neat_${value}`);
 * console.log(result);
 * > { neat_1: 1, neat_2: 2, neat_3: 3 }
 */
```

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## References

 - [_.mapKeys](https://lodash.com/docs/4.17.15#mapKeys)

**Comment by evanplaice** [comment]
Added in 0.54
