### ISSUE TITLE
arrays.unzip

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#124]
unzip accepts an array of zipped elements and returns them to their pre zipped arrangement as collections by element index in zipped arrays.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

Implementation can follow Lodash as there is no "MSDN" unzip which was used in the zip implementation.

However, zip's current implementation has some differences, like accepting a predicate and how it deals with different sized input arrays. these should be decided on and one or the other implementation updated.
```
const res = array.unzip([['a', 1, true], ['b', 2, false]])
console.log(res)
> [['a', 'b'], [1, 2], [true, false]]
```

## References 

 - [_.unzip](https://lodash.com/docs/4.17.15#unzip)

**Comment by evanplaice** [comment]
Added in 0.55
