### ISSUE TITLE
objects.merge

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#126]
Merges objects to return a single object like assign. However, array and object property values are merged recursively while other values are overwritten if the have the same key.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
var object = {
  'a': [{ 'b': 2 }, { 'd': 4 }]
};
 
var other = {
  'a': [{ 'c': 3 }, { 'e': 5 }]
};
 
const res = objects.merge(object, other);
console.log(res)
> { 'a': [{ 'b': 2, 'c': 3 }, { 'd': 4, 'e': 5 }] }
```

## References 

 - [_.merge](https://lodash.com/docs/4.17.15#merge)

**Comment by evanplaice** [comment]
Added in 0.56
