### ISSUE TITLE
object.defaults

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#131]
"Defaults" combines enumerable string keyed properties of provided objects into a new object.
When iterated through from left to right, if key already exists on new object, it is ignored.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
const res = objects.defaults({ sound: "boink" }, { color: "orange" }, { sound: "floop" })
console.log(res)
> { sound: "boink",  color: "orange" }
```

## References 

 - [_.defaullts](https://lodash.com/docs/4.17.15#defaults)

**Comment by evanplaice** [comment]
Added in 0.58
