### ISSUE TITLE
objects.has

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#133]
Checks if path is a direct property of object.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
const result = objects.has({ front: [1, 3, 5], back: [37, 39] });
console.log(result, 'back[1]');
> true
```

## References 

 - [_.has](https://lodash.com/docs/4.17.15#has)

**Comment by jkvyff** [comment]
oops, wrong return type in the docs, should be boolean

**Comment by evanplaice** [comment]
Added in 0.59
