### ISSUE TITLE
arrays.without

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#135]
Creates a copy of the input array that does not contain any of the values to be excluded, using [SameValueZero](http://ecma-international.org/ecma-262/7.0/#sec-samevaluezero) for equality comparisons

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
const result = arrays.without([2, 1, [5], 3], 1, 2, [5])
console.log(result)
> [[5], 3]
```

## References 

 - [_.without](https://lodash.com/docs/4.17.15#without)

**Comment by evanplaice** [comment]
Added in 0.60
