### ISSUE TITLE
unset and omit

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#137]
Both "unset" and "omit" take a path for an object and delete the property at that path, though "unset" returns boolean while "omit" returns the object.

While it may still be useful to know if a property can be deleted, as unset would no longer mutate the object it would be considerably less useful. Also, perhaps "unset" provides different enough functionality to need a better name like "removable" or something.

## References 

 - [_.unset](https://lodash.com/docs/4.17.15#unset)
 - [_.omit](https://lodash.com/docs/4.17.15#omit)

**Comment by evanplaice** [comment]
Good point. Omit accomplishes the same end result, and testing for the presence of an object reference rather than a boolen return value is a trivial change.

I'm good with adding `unset` to the excluded list for now. It can always be added at a later date if users explicitly request it.

**Comment by evanplaice** [comment]
I added `unset` to the list of excluded operators.
