### ISSUE TITLE
objects.get

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#138]
Get returns the value at path of object. If the resolved value is undefined, the defaultValue is returned in its place.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
const result = objects.get({ front: [1, 3, 5], back: [37, 39] },  'back[1]');
console.log(result);
> 39

const result1 = objects.get({ front: [1, 3, 5], back: [37, 39] }, ['front', 4], 'nothing there');
console.log(result1);
> 'nothing there'
```

## References 

 - [_.get](https://lodash.com/docs/4.17.15#get)

**Comment by evanplaice** [comment]
Added in 0.61
