### ISSUE TITLE
objects.mapValues

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#140]
Creates an object with the same keys as object and values generated by running each own enumerable string keyed property of object thru iteratee. The iteratee is invoked with three arguments:
(value, key, object).

## Checklist

- [ ] implementation
- [ ] tests
- [ ] jsdoc

## Details
Note: support differs from Lodash by not offering string property path shorthand, must be a function.

```
const result = objects.mapValues({ a: 1, b: 2, c: 3 }, value => `neat_${value}`);
console.log(result)
> { a: 'neat_1', b: 'neat_2', c: 'neat_3' }
```

## References 

 - [_.mapValues](https://lodash.com/docs/4.17.15#mapValues)

**Comment by evanplaice** [comment]
Good call leaving the string version. Map should represent a transition/function, not property lookup via string.

**Comment by evanplaice** [comment]
Added in 0.62
