### ISSUE TITLE
mapKeys and mapValues implementation

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#142]
mapKeys currently differs from mapValues by not allowing just the object to be passed without any function and it would be nice to have them have more similar implementations. 

### We have a few options to fix this:
1. Restrict the ability to pass no function on mapValues
2. Use an implementation closer to Lodash's spec by having a default function of (x) => x
3. Change mapKeys to simply return the object if no function exists to change it's state

### Notes for each:
1. I like that ability to pass no function, but if it does nothing and has strict number and type of params, making them both mandatory may be best.
2. Originally wanted to do this one, as it is to reference spec, but has strange consequence on mapKeys where:
```
mapKeys({ a: 1, b: 2 })
> {1: 1, 2: 2}
```
3. My current implementation, but just serves as a quieter way of allowing the param to be optional while not doing what I think is strange behavior. Also saving cycles.

## References 

 - [_.mapKeys](https://lodash.com/docs/4.17.15#mapKeys)
 - [_.mapValues](https://lodash.com/docs/4.17.15#mapValues)

**Comment by evanplaice** [comment]
You made the right call with 3. Map is supposed to apply the function to each value, no function means no function applied. Not mutating the input object makes the most sense.

**Comment by evanplaice** [comment]
Fixed in 0.62.1
