### ISSUE TITLE
objects.forIn

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#144]
forIn iterates over own and inherited properties and invokes function on property with three arguments: (value, key, object). Returns input object.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
function TestObj() {
  this.a = 1;
  this.b = 2;
}
 
TestObj.prototype.c = 3;
 
objects.forIn(new TestObj(), (value, key, object) {
  console.log(key);
});
//  Logs 'a', 'b', then 'c'
> { a: 1, b: 2}
```

## References 

 - [_.forIn](https://lodash.com/docs/4.17.15#forIn)

**Comment by evanplaice** [comment]
Added in 0.63
