### ISSUE TITLE
arrays.xor

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#149]
Creates an array of unique values that is the symmetric difference of the given arrays.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
const result = xor([2, 1, 'a'],[2, 3], ['a', 'a', 'c'])
console.log(result)
> [1, 3, 'c']
```

## References 

 - [_.xor](https://lodash.com/docs/4.17.15#xor)

**Comment by evanplaice** [comment]
Added in 0.65

**Comment by evanplaice** [comment]
@jkvyff Great Job! That concludes the `arrays` operators for 1.0. I'll run through the planning for the `strings` operators so you have more to pick and choose from.
