### ISSUE TITLE
objects.transform

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#151]
Transform, transforms an object to a new accumulator object which is the result of running each of its own enumerable string keyed properties through an iteratee function.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details
- Similar to reduce, but you don't need to return a value in function, just effect the accumulator and accumulator of the same type as input object will be used if none supplied
- Can only use an accumulator object(array || object)
- Returning false in function will stop iteration early.
- The function is invoked with four arguments: 
  - (accumulator, value, key, object) on objects
  - (accumulator, value, index, object) on arrays

```
const res = transform([2, 3, 4], (result, n) => {
  result.push(n *= n);
  return n % 2 == 0;
}, ['a']);
console.log(res);
> ['a', 4, 9]
```

## References 

 - [_.transform](https://lodash.com/docs/4.17.15#transform)

**Comment by evanplaice** [comment]
Added in 0.68
