### ISSUE TITLE
omit to be removed in Lodash 5.0.0

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#153]
Just noticed "omit" is to be removed in favor of "pick" for Lodash's next big release.
Is there enough utility for us to support it?

## Notes 

I think it would still be useful, but it will likely and up a slower implementation than pick like it is for Lodash.

## References 

 - [Lodash Roadmap](https://github.com/lodash/lodash/wiki/Roadmap)
- [_.pick](https://lodash.com/docs/4.17.15#pick)
- [_.omit](https://lodash.com/docs/4.17.15#omit)

**Comment by evanplaice** [comment]
I'm good with leaving it out

**Comment by evanplaice** [comment]
Looking through the Lodash changelog I noticed a few other changes worth considering.

_.flatten is changing to be shallow by default. I think we can match this by renaming the current flat -> flatten and remove the existing flatten implementation altogether.

The Collections secrton is being removed and the operators that aren't removed will be consolidsted into the array and object sections. It'll probably be worthwhile to track this.

**Comment by evanplaice** [comment]
`objects.omit` is excluded and `objects.pick` remains. Closing this as resolved.
