### ISSUE TITLE
objects.result

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#154]
Result, returns the value at path of object. If the resolved value is undefined, the defaultValue is returned in its place. If the returned value would be a function, it is resolved with a this binding to the object.

## Checklist

- [ ] implementation
- [ ] tests
- [ ] jsdoc

## Details

```
const obj = { front: [1, 3, 5], back: [() => 15, () => 19] };
console.log(objects.result(obj, 'back[1]'));
> 19
```

```
const obj = { front: [1, 3, 5], back: [37, 39] };
const func = (x) => { return x+7; }
console.log(objects.result(obj, ['front', 5], func(3)));
> 10
```

## References 

 - [_.result](https://lodash.com/docs/4.17.15#result)

**Comment by evanplaice** [comment]
Added in 0.66
