### ISSUE TITLE
objects.assign

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#158]
Assign merges object properties from all supplied objects. If a property already exists, then it is overwritten when merged from left to right.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
const someObj = { hold: 44, fast: 14 };
const result = objects.assign(someObj, { hold: 25, your: 19, horses: 4 });
console.log(result);
> { hold: 25, fast: 14, your: 19, horses: 4 }
```

## References 

 - [_.assign](https://lodash.com/docs/4.17.15#assign)

**Comment by evanplaice** [comment]
Added in 0.67
