### ISSUE TITLE
Implementation detail in Merge

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#160]
In implementing merge, I choose to include that if at a certain level of merging, when merging an array into an array  and comparing values that aren't undefined or other objects, the function will check if an arrays value exists in the other array. If it doesn't exist it will push the value to the end of the array to merge them.

However, this could make the function much slower with bigger arrays. In checking how Lodash treated this case, they treat an array like an object so each element only compares with the element of the same index(key).

## Expected behaviour

merge({ 'a': { 'b': [ 3, 4, 15] } }, { 'a': { 'b': [9, 18]} })
> { a: { b: [ 9, 18, 15 ] } }

## Actual behaviour

merge({ 'a': { 'b': [ 3, 4, 15] } }, { 'a': { 'b': [9, 18]} }))
> { a: { b: [ 3, 4, 15, 9, 18 ] } }

## References 

 - [_.merge](https://lodash.com/docs/4.17.15#merge)

**Comment by evanplaice** [comment]
I'm good with this :+1: 

I wonder where Lodash's version of merge was sourced from. I assume it would work like a union (ie how you implemented it) but that's clearly not the case.

Good catch BTW, that's a pretty obscure bug.

**Comment by evanplaice** [comment]
Fixed in 0.67.2
