### ISSUE TITLE
strings.camelCase

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#165]
returns a string converted to camelcase

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
console.log(strings.camelCase('   cheese23bread7butter61   '));
> 'cheese23Bread7Butter61'
 
console.log(strings.camelCase('--firm-shake--'));
> 'firmShake'
 
console.log(strings.camelCase('__WOLF_TIMBER__'));
> 'wolfTimber'
```
## References 

 - [_.camelCase](https://lodash.com/docs/4.17.15#camelCase)

**Comment by evanplaice** [comment]
Added in 0.70
