### ISSUE TITLE
strings.pad

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#167]
Pads string on the left and right sides if it's shorter than length. Padding characters are truncated if they can't be evenly divided by length.
## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
console.log(strings.pad('abcabc', 9));
> ' abcabc  '
```

```
console.log(strings.pad('abcabc', 15, '_-+'));
> ' _-+_abcabc_-+_-'
```

## References 

 - [_.pad](https://lodash.com/docs/4.17.15#pad)

**Comment by evanplaice** [comment]
Added in 0.71
