### ISSUE TITLE
strings.capitalize

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#169]
Converts the first character of string to upper case and the remaining to lower case.

## Checklist

- [ ] implementation
- [ ] tests
- [ ] jsdoc

## Details

```
console.log(strings.capitalize('flying CAR'));
>'Flying car'
```

## References 

 - [_.capitalize](https://lodash.com/docs/4.17.15#capitalize)

**Comment by evanplaice** [comment]
Closed as invalid b/c performing this transform this with reduce would be really inefficient.
