### ISSUE TITLE
strings.truncate

### ISSUE THREAD

**Issue by evanplaice** [vanillaes/absurdum#183]
Truncates string if it's longer than the given maximum string length. The last characters of the truncated string are replaced with the omission string

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```javascript
console.log(strings.truncate('hi-diddly-ho there, neighborino', { 'length': 24, 'separator': /,? +/});
>'hi-diddly-ho there...'
```

## References

- [_.truncate - Lodash](https://lodash.com/docs/4.17.15#truncate)

**Comment by jkvyff** [comment]
This method doesn't really map well to reduce as it requires limiting the string to (options['length'] - the separator), then finding the last occurrence of a (regex/string) within that string and adding the separator after to that. Most of the work is in formatting and using regex to do that slightly unusual thing.

**Comment by evanplaice** [comment]
Added in 0.79
