### ISSUE TITLE
Replace objects.include/exclude -> objects.filter?

### ISSUE THREAD

**Issue by evanplaice** [vanillaes/absurdum#203]
Include/exclude are my own invention. Their purpose is to selectively add/remove properties from an object by key. The original `include` was actually named `filterByKey`. Also, `object.includes` overlaps functionality with `objects.pick`.

That's good an all but I think it would be much more beneficial to have an object-specific filter method that allows the ability to include/exclude based on a function that returns true/false.

## Notes

```javascript
console.log(objects.filter({ small: "ant", medium: "dog", big: "elephant" }, (key, value) => ['small', 'big'].includes(key)));
> { small: 'ant', big: 'elephant' }
```

## References

- [objects.exclude](https://github.com/vanillaes/absurdum/issues/14)
- [objects.include](https://github.com/vanillaes/absurdum/issues/13)
- [objects.pick](https://github.com/vanillaes/absurdum/issues/108)

**Comment by evanplaice** [comment]
@jkvyff What do you think?

**Comment by jkvyff** [comment]
It would make sense to make it more flexible to the type of filtering desired. 

Followup,  would you want to retain the dual focus of include/exclude with a filter/remove functionality but the remove function would return the object with instead of properties removed?

**Comment by jkvyff** [comment]
I like the idea of just having filter to have a very flexible function while using not operator in user provided function to handle negation cases.
