### ISSUE TITLE
IE Compatibility

### ISSUE THREAD

**Issue by evanplaice** [vanillaes/absurdum#211]
IE compatibility is a worthwhile target. This issue tracks the work to make that happen.

## Checklist

- [x] objects.defaultsDeep - replace Object.entries -> Object.keys v0.81.12
- [x] objects.forIn - replace Object.entries -> Object.keys v0.81.13
- [x] objects.invert - replace Object.entries -> object.keys v0.81.14
- [x] objects.mapKeys - replace Object.entries -> Object.keys v0.81.15
- [x] objects.mapValues - replace Object.entries -> Object.keys v0.81.16
- [x] objects.merge - replace Object.entries -> Object.keys v0.81.18
- [x] objects.transform - replace Object.entries -> Object.keys v0.81.17
- [x] object.values - replace Object.values -> Object.keys v0.81.19

## References

- #205

**Comment by jkvyff** [comment]
Object.values would also need a replacement - [tc39 polyfill](https://github.com/tc39/proposal-object-values-entries/blob/master/polyfill.js)

**Comment by evanplaice** [comment]
Added
