### ISSUE TITLE
objects.filter

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#213]
Filter iterates over an object and applies a function to each property, for all properties where the function returns true return that property in a new object.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

```
console.log(objects.filter({ small: "ant", medium: "dog", big: "elephant" }, (key, value) => ['small', 'big'].includes(key)));
> { small: 'ant', big: 'elephant' }
```

## References 

 - [_.filter](https://lodash.com/docs/4.17.15#filter)

**Comment by evanplaice** [comment]
Damn... You're fast. I was going to implement this tonight. I'll take care of removing include/exclude instead.

**Comment by evanplaice** [comment]
Added in 0.81
