### ISSUE TITLE
Pre 1.0 Release Leftovers

### ISSUE THREAD

**Issue by evanplaice** [vanillaes/absurdum#222]
What else needs to be done before the 1.0 release drops?

**Comment by evanplaice** [comment]
I have exhaustingly reviewed the list of operators. Everything that should be included is included, everything that shouldn't be included isn't. The only exceptions are `map`/`filter`. Should these be removed as well?

IMO, the README.md could use some work. Remove the "Funky Name" and "What's the Point" sections. Maybe add a section explainer that talks about the functional nature of these components.

Also, I think the operators listing would look better as a table. Possibly with columns for polyfill and links to the lodash equivalent.

@jkvyff What do you think?

**Comment by jkvyff** [comment]
By a polyfill column, do you mean the functions that would require a polyfill to be IE compatible?

**Comment by evanplaice** [comment]
Functions that could be used as polyfills because they don't exist in IE11

Name it "Polyfills" then add a link to the function/method on MDN. 

I have the table partway done. I'll ping you to check it out once it's ready.

**Comment by jkvyff** [comment]
A few notes:
- Both map and filter seem to be kept in many other utility libraries, while they aren't so useful as they are methods already built into the language. I do believe they serve an important purpose in being one of the first methods someone looking at source could turn to when seeing what an implementation prioritizes through a simple example.
- Sounds good on the readme, ill do that today
- should documentation names be standardized more (eg. predicate, func | element, value)?

**Comment by evanplaice** [comment]
- Cool
- Good point about map/filter. I was a bit conflicted b/c I've been in chopping block mode lately but I agree.
- don't worry about the operators table in the README.md. I'll have that done this afternoon.
- Yes, I wasn't sure if we should do this before or after 1.0. ITT, all the docs could use a good once-over to locate and fix any inconsistencies.

I'm trying to find a better JSDoc -> MD conversion tool so we have more control over the output and can support multiple example tags. ESDoc would be the most promising but the project is currently dead and I haven't received a response back from the maintainer so it's probably a dead end.

**Comment by jkvyff** [comment]
Might be able to reach the [ESDoc2](https://github.com/esdoc2/esdoc2) person, though project is about the same level of active.

**Comment by evanplaice** [comment]
Probably not worth the time. I don't just need ESDoc, I would also need to finish building the Markdown output.

**Comment by jkvyff** [comment]
I'm down to do a standardization of docs before 1.0, as it would still just be what is glaring for me.

Do:
- standardize terminology, as mentioned before
- fix typos or misspellings
- adding optional before optional parameter description

Delay:
- Rewordings of definitions for clarity
- Adding examples for each type of way to use function

**Comment by evanplaice** [comment]
Sounds good to me.

**Comment by evanplaice** [comment]
Are we good to drop 1.0?

**Comment by evanplaice** [comment]
Can you create a PR for this? Put the logo(s) in an 'assets' folder at the project root.

**Comment by evanplaice** [comment]
1.0 Released :+1:
