### ISSUE TITLE
Should Absurdum have a Logo?

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#223]
Was wondering if Absurdum would need a logo?

Tried my hand at a few basic ones.

## Notes 

Had these things in mind:
- Bold lines to be recognizable even when very small
 - Repeated shape at different sizes and orientations to connect loosely with how reduce adjusts and minimizes data.
- Abstract shapes that vaguely resemble creatures eyes, a loose nod to absurdist art
- Simple typographic logo, follow pattern of using first character of a name (lowercase 'a')
- Simple single color that can be enhanced with gradients and texture at larger sizes

## References 

<img width="908" alt="Screen Shot 2020-01-16 at 10 32 11 AM" src="https://user-images.githubusercontent.com/8835646/72552571-00c80580-384c-11ea-8c04-31c4a580c5cb.png">

**Comment by evanplaice** [comment]
Yes, it definitely should

3 might have issues at smaller sizes. 4 the reduction in size metaphor stands out the most. 1 is the modt obvious.

**Comment by jkvyff** [comment]
I agree that on 1 and 4, perhaps a slight preference for 1 as I think it might gain more in being read as an 'a' then how much it loses by not being the same shape reduced twice.

If you are okay with it, we can try out slight tweaks to amount of rounding or gap for 'a' tail, otherwise the next question would be color. 

I can send a vector file over for you to mess with if you would like.

**Comment by evanplaice** [comment]
TBH, I like 1 as-is. Either way, the final decision on this is all yours.

There aren't any specific branding guidelines for this org so the color should be whatever you think looks best.

**Comment by jkvyff** [comment]
I like the orange, and found that it looks fairly nice with the 'Lato-semibold' font.

<img width="732" alt="Screen Shot 2020-01-19 at 1 56 11 PM" src="https://user-images.githubusercontent.com/8835646/72689178-9c16e000-3ac3-11ea-8418-8dc50a3fa16d.png">

**Comment by evanplaice** [comment]
Wow... That looks slick

I granted you Admin privileges for the Absurdum repo. If you go to settings, on the main page there's a spot to set the 'social preview' for the project.

**Comment by evanplaice** [comment]
Added in 0.82.0
