### ISSUE TITLE
arrays.indexOf

### ISSUE THREAD

**Issue by evanplaice** [vanillaes/absurdum#41]
The indexOf() method returns the first index at which a given element can be found in the array, or -1 if it is not present.

## Checklist

- [x] implemented
- [x] documented
- [x] tested
- [x] linted

## Details

```javascript
var beasts = ['ant', 'bison', 'camel', 'duck', 'bison'];

console.log(beasts.indexOf('bison'));
// expected output: 1

// start from index 2
console.log(beasts.indexOf('bison', 2));
// expected output: 4

console.log(beasts.indexOf('giraffe'));
// expected output: -1
```

## References

 - [Array.prototype.indexOf - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf)

**Comment by jkvyff** [comment]
Heya, tried my hand at this method. I think I followed the spirit, but let me know about using if statements before the reduce. All the best.a

**Comment by evanplaice** [comment]
If statements to exit early on edge cases are acceptable.

Would you mind removing the builds (ie `.cjs/.esm`) and generated doc (ie `.md`). As of the update early today, all build steps (ie doc, bundles, docs, typings) are automatically applied when a new version is published. I still need to update `CONTRIBUTING.md` to reflect this.

Otherwise LGTM

**Comment by evanplaice** [comment]
Almost forgot. Great job on this, for the first person (other than me) to implement a new operator you managed to cover all the bases. I'm impressed.

**Comment by evanplaice** [comment]
Thank you for your contribution :+1:

If you'd like your name added to the `contributors` in package.json, feel free to add it in another PR. 

Here's an example

```json
  "contributors": [
    {
      "name": "Evan Plaice",
      "email": "evanplaice@gmail.com",
      "url": "http://evanplaice.com"
    }
  ],
```
The `email` and `url` fields are optional.

Otherwise, just close this issue again.

**Comment by evanplaice** [comment]
Added in 0.20

**Comment by evanplaice** [comment]
Removed in 0.74.3
