### ISSUE TITLE
arrays.frequency

### ISSUE THREAD

**Issue by evanplaice** [vanillaes/absurdum#56]
Takes an array of similar values and returns an object mapping each unique item to the number of items it occurs in the array.

## Checklist

- [x] implementation
- [x] tests
- [x] jsdoc

## Details

Reference implementation

```javascript
const input = ['a', 'b', 'a', 'c', 'a', 'c', 'b'];
const frequencies = input.reduce((acc, curr) => {
  acc[curr] = !acc[curr] ? 1 : ++acc[curr];
  return acc;
}, {});
console.log(frequencies);
> {
>   a: 3,
>   b: 2,
>   c: 2
> }
```

## References

 - [tweet](https://twitter.com/Carlillo/status/1192526222208749569?s=20)

**Comment by evanplaice** [comment]
@JosiahRooney FYI, I assigned this issue to myself since I am unable to assign it to you directly.

**Comment by evanplaice** [comment]
@JosiahRooney Are you still planning to add this operator? Do you need help?

**Comment by jkvyff** [comment]
I just went with the reference implementation

**Comment by evanplaice** [comment]
Added in 0.48
